### ISSUE TITLE
Is it possible to write points with siridb-prompt?

### ISSUE THREAD

**Issue by bigreybear** [transceptor-technology/siridb-prompt#8]
I am using the prompt to manipulate my SiriDB, but I did not see how to wirte data points with command line.

Is it possible to do it?

**Comment by joente** [comment]
It is not supported by the prompt at the moment, but not that hard to create as the underlying client supports the insert of data points. For example, the prompt may be changed to accept an argument like `--insert-json-file` which accepts a JSON file with data points.

**Comment by bigreybear** [comment]
> 

Hi, Thank you! And one more question: is it possible to set tag to a series and insert its data points at the same time?

**Comment by joente** [comment]
No, but this would be a nice suggestion for SiriDB v3. We have recently created a discussion board and already have a few other good features for the next version of SiriDB: https://github.com/orgs/SiriDB/discussions/7

**Comment by bigreybear** [comment]
> No, but this would be a nice suggestion for SiriDB v3. We have recently created a discussion board and already have a few other good features for the next version of SiriDB: https://github.com/orgs/SiriDB/discussions/7

That is cool ! I will follow these threads, thank you again, good day!
